# Generated by Django 3.2.2 on 2021-09-30 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
    ]
